export default {
  "breast-cancer": "Breast Cancer",
  goiter: "Goiter",
  "graves-disease": "Graves' Disease",
  solitary: "Solitary Thyroid Nodule",
  "cystic-hygroma": "Cystic Hygroma",
  "thyroglossal-cyst": "Thyroglossal-cyst",
  goo: "Gastric Outlet Obstruction",
  "gastric-cancer": "Gastric Cancer",
  "peptic-ulcer": "Peptic Ulcer",
  pancreatitis: "Severe Acute Pancreatitis",
  "surgical-jaundice": "Surgical Jaundice",
  "ca-pancreas": "Ca Head of Pancreas",
  "pseudocyst-of-pancreas": "Psuedocyst of Pancreas",
  "oesophageal-varices": "Oesophageal Varices",
};
