export default {
  index: "Introduction",
  cardiology: "Cardiology",
  respiration: "Respiratory",
  hepatology: "Hepatology",
  neurology: "Neurology",
  nephrology: "Nephrology",
  haematology: "Haematology",
  rheumatology: "Rheumatology",
  "diabetes-mellitus": "Diabetes Mellitus",
  infection: "Infection",
  endocrinology: "Endocrinology",
  "snake-bite": "Snake Bite",
  summary: "Summary",
};
