export default {
  wounds: "Wounds",
  nutritions: "Nutritions",
  haemorrhage: "Haemorrhage",
  "blood-transfusion": "Blood Transfusion",
  shock: "Shock",
  "sterilization-disinfection": "Sterilization & Disinfection",
  "surgery-in-malignancy": "Surgery in Malignancy",
  tetanus: "Tetanus",
  "pre-operative-preparation": "Pre-Op Preparation",
  "who-surgical-safety-checklist": "WHO Surgical Safety Checklist",
  "post-operative-fever": "Post-Op Fever",
  "post-operative-complications": "Post-Op Complications",
  "minimally-invasive-surgery": "Minimally Invasive Surgery",
  gangrene: "Gangrene",
};
