export default {
  nutritions: "Nutritions",
  "blood-transfusion": "Blood Transfusion",
  shock: "Shock",
  ssi: "Surgical Site Infection",
  tetanus: "Tetanus",
  burns: "Burns",
  neoplasia: "Neoplasia",
  "pre-op": "Pre-operative Preparations",
  "post-op": "Post-operative Complications",
  "post-op-fever": "Post-op Fever",
  mas: "Minimally Access Surgery",
  haemorrhage: "Haemorrhage",
  "tb-lymphadenitis": "TB Lymphadenitis",
  tracheostomy: "Tracheostomy",
};
